"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os  # ← 新增

# === 路徑 ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === 安全 / 偵錯（開發期） ===
SECRET_KEY = 'django-insecure-*_w*p_8u)xnbqgq-+ui-z2-k8#ayk)icr=gz26#0akb_sto9u4'  # TODO: 正式環境改用環境變數
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "0.0.0.0"]  # ← 允許本機與 runserver 綁 0.0.0.0

# === 應用程式 ===
INSTALLED_APPS = [
    # 內建
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方（開發期先裝這三個）
    'rest_framework',         # ← 新增
    'corsheaders',            # ← 新增

    # 你建立的 Apps
    'accounts',               # ← 新增
    'annotations',            # ← 新增
    'ocr_service',            # ← 新增
]

# === 中介層 ===
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # ← 建議放最前或至少在 CommonMiddleware 之前
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# === 資料庫（開發期 SQLite） ===
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# === 密碼驗證 ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === 語系 / 時區 ===
LANGUAGE_CODE = 'zh-hant'      # ← 符合你的使用情境
TIME_ZONE = 'Asia/Taipei'      # ← 台北時區
USE_I18N = True
USE_TZ = True

# === 靜態檔 ===
STATIC_URL = 'static/'

# === 主要鍵型別 ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === CORS（開發期先放寬；正式環境改白名單） ===
CORS_ALLOW_ALL_ORIGINS = True  # ← 前端 Vite 走 /api 代理時較方便

# === DRF（開發期先開放；登入完成後改成 IsAuthenticated） ===
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ["rest_framework.authentication.SessionAuthentication"],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
}

# === Redis 連線（給 RQ 用；沒設環境變數時預設本機） ===
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379")
